#!/bin/bash

# put this script directly in /etc/cron.daily it will run automatically.
# configure postfix to get the mail

# email subject
SUBJECT="VIRUS DETECTED ON `hostname`!!!"
# Email To ?
EMAIL="my@mail.com"
# Log location
LOG=/var/log/clamav/scan.log

check_scan () {

    # Check the last set of results. If there are any "Infected" counts that aren't zero, we have a problem.
        if [ `tail -n 12 ${LOG}  | grep Infected | grep -v 0 | wc -l` != 0 ]
	    then
	            EMAILMESSAGE=`mktemp /tmp/virus-alert.XXXXX`
		            echo "To: ${EMAIL}" >>  ${EMAILMESSAGE}
			            echo "From: my@mail.com" >>  ${EMAILMESSAGE}
				            echo "Subject: ${SUBJECT}" >>  ${EMAILMESSAGE}
					            echo "Importance: High" >> ${EMAILMESSAGE}
						            echo "X-Priority: 1" >> ${EMAILMESSAGE}
							            echo "`tail -n 50 ${LOG}`" >> ${EMAILMESSAGE}
								            sendmail -t < ${EMAILMESSAGE}
									        fi

}

clamscan -r / --exclude-dir=/sys/ --quiet --infected --log=${LOG}

check_scan
