#!/bin/bash
# author: aurelien DESBRIERES
# license: GPL V3 or later!
# contact: aurelien(at)hackers(dot)camp

# share configuration between servers

# How-to: sudo cp populate /usr/bin/
#         sudo chmod +x /usr/bin/populate

# registration of the key
if [ ! -S ~/.ssh/ssh_auth_sock ]; then
    eval "$(ssh-agent)"
    ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi
export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
ssh-add -l | grep "The agent has no identities" && ssh-add

# Send the stuff
cd ~/
scp command.md .bashrc .emacs icecloud:~/
scp command.md .bashrc .emacs icebreaker:~/
scp command.md .bashrc .emacs subair:~/
printf "done!\n"
